# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_schedulerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerecord',
            name='classroom',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='schedulerecord',
            name='discipline',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='schedulerecord',
            name='group',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='schedulerecord',
            name='teacher',
            field=models.CharField(max_length=264),
        ),
    ]
