# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20191105_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerecord',
            name='dayWeek',
            field=models.CharField(max_length=264),
        ),
    ]
