# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20191120_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerecord',
            name='course',
            field=models.CharField(default=0, max_length=264),
            preserve_default=False,
        ),
    ]
